### ISSUE TITLE
ModuleNotFoundError: No module name 'kivy.adapters'

### ISSUE THREAD

**Issue by yemi-Jump** [KeyWeeUsr/KivyInstaller#19]
I can't run the program. When I type python -m designer this is the TraceBack I get:

```python
Traceback (most recent call last):
   File "C:\Python36\lib\runpy.py", line 193, in _run_module_as_main
     "__main__", mod_spec)
   File "C:\Python36\lib\runpy.py", line 85, in _run_code
     exec(code, run_globals)
   File "C:\Users\tonya\Desktop\kivy-designer\designer\__main__.py", line 3, in <module>
     from designer.app import DesignerApp
   File "C:\Users\tonya\Desktop\kivy-designer\designer\app.py", line 12, in <module>
     from designer.components.designer_content import DesignerContent
   File "C:\Users\tonya\Desktop\kivy-designer\designer\components\designer_content.py", line 5, in <module>
     from designer.uix.py_code_input import PyScrollView
   File "C:\Users\tonya\Desktop\kivy-designer\designer\uix\py_code_input.py", line 3, in <module>
     from designer.uix.completion_bubble import CompletionBubble
   File "C:\Users\tonya\Desktop\kivy-designer\designer\uix\completion_bubble.py", line 1, in <module>
     from kivy.adapters.listadapter import ListAdapter
 ModuleNotFoundError: No module named 'kivy.adapters'
```

**@KeyWeeUsr Edit:** Reverted leaving an empty closed issue.

**Comment by 8qBITs** [comment]
How did you solve this?

**Comment by Oolev** [comment]
This functionality is deprecated in newer versions of kivy and since the project has been discontinued (or is not maintained any more) it gives this error.

**Comment by MysteriousSonOfGod** [comment]
Hi, please, so what do we to designer ?
